"use client"
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../provider";
import { AppbarClient } from "../components/AppbarClient";
import { usePathname, useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Turborepo",
//   description: "Generated by create turbo",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  const router = useRouter();
  const pathname = usePathname();

  // Define paths where AppBar should not be displayed
  const noAppBarPaths = ['/signin'];
  const noAppBarPaths2 = ['signup'];
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
        <div>
          {/* <AppbarClient></AppbarClient> */}
          {!noAppBarPaths.includes(pathname) && <AppbarClient />}
        </div>
          {children}
        </body>
      </Providers>
    </html>
  );
}
